[2023-05-11T08:10:37.854+0000] {warnings.py:110} WARNING - /usr/local/lib/python3.7/site-packages/***/models/taskinstance.py:871: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti: TaskInstance | None = qry.with_for_update().one_or_none()

[2023-05-11T08:10:37.912+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: spark_process_data_13.spark_job_clean_data_by_ssh manual__2023-05-11T08:10:35.418182+00:00 [queued]>
[2023-05-11T08:10:37.953+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: spark_process_data_13.spark_job_clean_data_by_ssh manual__2023-05-11T08:10:35.418182+00:00 [queued]>
[2023-05-11T08:10:37.954+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-05-11T08:10:37.954+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2023-05-11T08:10:37.955+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-05-11T08:10:38.016+0000] {taskinstance.py:1383} INFO - Executing <Task(SSHOperator): spark_job_clean_data_by_ssh> on 2023-05-11 08:10:35.418182+00:00
[2023-05-11T08:10:38.029+0000] {standard_task_runner.py:54} INFO - Started process 3089 to run task
[2023-05-11T08:10:38.040+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'spark_process_data_13', 'spark_job_clean_data_by_ssh', 'manual__2023-05-11T08:10:35.418182+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/spark_process_scheduler.py', '--cfg-path', '/tmp/tmpotutk3hl']
[2023-05-11T08:10:38.041+0000] {standard_task_runner.py:83} INFO - Job 71: Subtask spark_job_clean_data_by_ssh
[2023-05-11T08:10:38.044+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/spark_process_scheduler.py
[2023-05-11T08:10:38.367+0000] {task_command.py:384} INFO - Running <TaskInstance: spark_process_data_13.spark_job_clean_data_by_ssh manual__2023-05-11T08:10:35.418182+00:00 [running]> on host 09877495cfa0
[2023-05-11T08:10:38.381+0000] {warnings.py:110} WARNING - /usr/local/lib/python3.7/site-packages/***/models/taskinstance.py:873: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti = qry.one_or_none()

[2023-05-11T08:10:38.688+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=pioneer22022001@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=spark_process_data_13
AIRFLOW_CTX_TASK_ID=spark_job_clean_data_by_ssh
AIRFLOW_CTX_EXECUTION_DATE=2023-05-11T08:10:35.418182+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-11T08:10:35.418182+00:00
[2023-05-11T08:10:38.690+0000] {ssh.py:135} INFO - Creating ssh_client
[2023-05-11T08:10:38.822+0000] {ssh.py:112} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2023-05-11T08:10:38.870+0000] {base.py:71} INFO - Using connection ID 'ssh_connection_spark' for task execution.
[2023-05-11T08:10:38.873+0000] {ssh.py:299} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2023-05-11T08:10:38.899+0000] {transport.py:1873} INFO - Connected (version 2.0, client OpenSSH_7.9p1)
[2023-05-11T08:10:39.026+0000] {transport.py:1873} INFO - Authentication (password) successful!
[2023-05-11T08:10:39.028+0000] {ssh.py:476} INFO - Running command: spark-submit --master spark://spark-master:7077 --conf spark.master=spark://spark-master:7077 --name spark_clean_data --verbose /opt/spark/app/preprocess_data.py
[2023-05-11T08:10:39.114+0000] {ssh.py:527} WARNING - bash: spark-submit: command not found
[2023-05-11T08:10:39.305+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/providers/ssh/operators/ssh.py", line 173, in execute
    result = self.run_ssh_client_command(ssh_client, self.command, context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/providers/ssh/operators/ssh.py", line 161, in run_ssh_client_command
    self.raise_for_status(exit_status, agg_stderr, context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/providers/ssh/operators/ssh.py", line 154, in raise_for_status
    raise AirflowException(f"SSH operator error: exit status = {exit_status}")
airflow.exceptions.AirflowException: SSH operator error: exit status = 127
[2023-05-11T08:10:39.349+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_process_data_13, task_id=spark_job_clean_data_by_ssh, execution_date=20230511T081035, start_date=20230511T081037, end_date=20230511T081039
[2023-05-11T08:10:39.433+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 71 for task spark_job_clean_data_by_ssh (SSH operator error: exit status = 127; 3089)
[2023-05-11T08:10:39.472+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-05-11T08:10:39.660+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
